#!/usr/bin/env bash
# Copies every image referenced by the ICPS28 proposal .tex files into
# public/assets/<category>/<slug>. Only referenced images are included.
set -euo pipefail

SRC="/home/dario/AISF/icps-pp/ICPS28_Project_Proposal"
DEST="/home/dario/AISF/icps-pp/icps28-website/public/assets"

copy() { # <src-rel> <dest-rel>
  local src="$SRC/$1"
  local dst="$DEST/$2"
  mkdir -p "$(dirname "$dst")"
  cp "$src" "$dst"
  echo "  $1 -> $2"
}

echo "== brand =="
copy "photos/AISF_LOGO_BG.png"          "brand/aisf-logo-bg.png"
copy "photos/logo_icps28.jpg"           "brand/logo-icps28.jpg"
copy "photos/filigrana.jpg"             "brand/filigrana.jpg"
copy "photos_orig/Firme.png"            "brand/firme.png"

echo "== oc (members + group) =="
copy "photos_orig/oc/gruppo.jpg"        "oc/gruppo.jpg"
copy "photos/oc/Cante.png"              "oc/federico-canterucci.png"
copy "photos/oc/Julia.png"              "oc/julia-favaro.png"
copy "photos/oc/Deb.png"                "oc/debora-marrone.png"
copy "photos/oc/Valerio.png"            "oc/valerio-tinari.png"
copy "photos/oc/Luca.png"               "oc/luca-attina.png"
copy "photos/oc/Cla.png"                "oc/claudia-franco.png"
copy "photos/oc/Giacomo.png"            "oc/giacomo-galli.png"
copy "photos/oc/Cicca.png"              "oc/roberto-ciccarelli.png"
copy "photos_orig/oc/Adele.png"         "oc/adele-peluso.png"
copy "photos/oc/Davide.png"             "oc/davide-perillo.png"
copy "photos_orig/oc/Tomislav.png"      "oc/tomislav-vojvodic.png"
copy "photos/oc/Francesco.png"          "oc/francesco-ottone.png"
copy "photos/oc/Giorgia.png"            "oc/giorgia-cantore.png"
copy "photos/oc/Raimondo.png"           "oc/raimondo-lucariello.png"
copy "photos/oc/Sara.png"               "oc/sara-atlante.png"
copy "photos/oc/Tassa.png"              "oc/valerio-tassarotti.png"
copy "photos/oc/Virginia.png"           "oc/virginia-marchignoli.png"
copy "photos/oc/Rares.png"              "oc/rares-drosu.png"
copy "photos/oc/Mario.png"              "oc/mario-lisciandrello.png"
copy "photos/oc/Elisa.png"              "oc/elisa-sogno.png"
copy "photos/oc/Marta.png"              "oc/marta-giacomet.png"
copy "photos/oc/Dario.png"              "oc/dario-zarcone.png"
copy "photos/oc/Alice.png"              "oc/alice-dautilio.png"
copy "photos/oc/Claudio.png"            "oc/claudio-scarasciullo.png"
copy "photos/oc/Mattia.png"             "oc/mattia-magaletti.png"
copy "photos/oc/Lorenzo.png"            "oc/lorenzo-sabadini.png"
copy "photos/oc/Alessandro.png"         "oc/alessandro-lupi.png"
copy "photos/oc/Mara.png"               "oc/maria-rosaria-sivo.png"

echo "== cities =="
copy "photos/cities/image5.png"                  "cities/torino-panorama.png"
copy "photos/cities/image1.png"                  "cities/torino-piazza.png"
copy "photos/cities/mole antonelliana.png"       "cities/mole-antonelliana.png"
copy "photos/cities/Milano_skyline.jpg"          "cities/milano-skyline.jpg"
copy "photos/cities/Castello-Sforzesco.jpg"      "cities/castello-sforzesco.jpg"
copy "photos/cities/Navigli.jpg"                 "cities/navigli.jpg"

echo "== accomodation =="
copy "photos/accomodation/Program_A.png"             "accomodation/program-a.png"
copy "photos/accomodation/Program_B.png"             "accomodation/program-b.png"
copy "photos/accomodation/CX_TO_Marconi.png"         "accomodation/campusx-torino-marconi.png"
copy "photos/accomodation/CX_TO_Vanchiglia.png"      "accomodation/campusx-torino-vanchiglia.png"
copy "photos/accomodation/CX_MI_Bicocca.png"         "accomodation/campusx-milano-bicocca.png"
copy "photos/accomodation/Meininger_MI.png"          "accomodation/meininger-milano.png"
copy "photos/accomodation/Olimpia_TO.png"            "accomodation/olimpia-torino.png"
copy "photos/accomodation/Bicocca_Magna.png"         "accomodation/bicocca-magna.png"
copy "photos/accomodation/Shuster_Milano.png"        "accomodation/casa-shuster.png"
copy "photos/accomodation/Palazzo_Nuovo_Torino.png"  "accomodation/palazzo-nuovo.png"
copy "photos/accomodation/Campus_Einaudi_Torino.png" "accomodation/campus-einaudi.png"

echo "== food =="
copy "photos/food/Pizza-cropped.png"            "food/pizza.png"
copy "photos/food/Cappuccino-cropped.png"       "food/cappuccino.png"
copy "photos/food/Tiramisu-cropped.png"         "food/tiramisu.png"
copy "photos/food/gorgonzola-cropped.png"       "food/gorgonzola.png"
copy "photos/food/panettone-cropped.png"        "food/panettone.png"
copy "photos/food/bagna cauda-cropped.png"      "food/bagna-cauda.png"
copy "photos/food/bicerin-cropped.png"          "food/bicerin.png"

echo "== speakers =="
copy "photos_orig/speaker/Gianotti.png"      "speakers/fabiola-gianotti.png"
copy "photos_orig/speaker/Tonelli.png"       "speakers/guido-tonelli.png"
copy "photos_orig/speaker/Maiani.png"        "speakers/luciano-maiani.png"
copy "photos_orig/speaker/Parisi.png"        "speakers/giorgio-parisi.png"
copy "photos_orig/speaker/Zapperi.png"       "speakers/stefano-zapperi.png"
copy "photos_orig/speaker/Battiston.png"     "speakers/federico-battiston.png"
copy "photos_orig/speaker/Ferlaino.png"      "speakers/francesca-ferlaino.png"
copy "photos_orig/speaker/Amano.png"         "speakers/hiroshi-amano.png"
copy "photos_orig/speaker/L'Huillier.png"    "speakers/anne-lhuillier.png"
copy "photos_orig/speaker/Maggiore.png"      "speakers/michele-maggiore.png"
copy "photos_orig/speaker/Rovelli.png"       "speakers/carlo-rovelli.png"
copy "photos_orig/speaker/Branchesi.png"     "speakers/marica-branchesi.png"
copy "photos_orig/speaker/Bisogni.png"       "speakers/maria-giuseppina-bisogni.png"
copy "photos_orig/speaker/Carrozza.png"      "speakers/maria-chiara-carrozza.png"
copy "photos_orig/speaker/Rossi.png"         "speakers/sandro-rossi.png"
copy "photos_orig/speaker/Gianotti2.png"     "speakers/fosca-giannotti.png"
copy "photos_orig/speaker/Bartoletti.png"    "speakers/ivana-bartoletti.png"
copy "photos_orig/speaker/Fabris.png"        "speakers/adriano-fabris.png"
copy "photos_orig/speaker/Broccoli.png"      "speakers/bobbybroccoli.png"
copy "photos_orig/speaker/Battiston2.png"    "speakers/roberto-battiston.png"
copy "photos_orig/speaker/Ferrero.png"       "speakers/andrea-ferrero.png"
copy "photos_orig/speaker/Scarpetta.png"     "speakers/ersilia-vaudo-scarpetta.png"
copy "photos_orig/speaker/Cristoforetti.png" "speakers/samanta-cristoforetti.png"
copy "photos_orig/speaker/Parmitano.png"     "speakers/luca-parmitano.png"

echo "== lab =="
copy "photos/lab/square-venaria.jpg"            "lab/venaria-reale.jpg"
copy "photos/lab/square-inrim.jpg"              "lab/inrim.jpg"
copy "photos/lab/square-marioboella.jpg"        "lab/links-mario-boella.jpg"
copy "photos/lab/square-polito.jpg"             "lab/politecnico-torino.jpg"
copy "photos/lab/square-merate.jpg"             "lab/merate-observatory.jpg"
copy "photos/lab/square-ifom.png"               "lab/ifom.jpg"
copy "photos/lab/square-lasa.jpg"               "lab/lasa.jpg"
copy "photos/lab/square-milanobicocca.jpg"      "lab/milano-bicocca.jpg"

echo "== social =="
copy "photos/programma sociale/Ca_Granda.jpg"          "social/ca-granda.jpg"
copy "photos/programma sociale/Genova.jpg"             "social/genova.jpg"
copy "photos/programma sociale/5Terre.jpg"             "social/cinque-terre.jpg"
copy "photos/programma sociale/Lago.jpg"               "social/lake-como.jpg"
copy "photos/programma sociale/Resinelli.jpg"          "social/pian-dei-resinelli.jpg"
copy "photos/programma sociale/Canzo.jpg"              "social/canzo.jpg"
copy "photos/programma sociale/Leonardo.jpg"           "social/leonardo.jpg"
copy "photos/programma sociale/Nations1.png"           "social/nations-1.png"
copy "photos/programma sociale/Nations2.png"           "social/nations-2.png"
copy "photos/programma sociale/Nations3.png"           "social/nations-3.png"
copy "photos/programma sociale/Alice_in_Turinland.png" "social/alice-in-turinland.png"
copy "photos/programma sociale/Museo_Egizio1.jpg"      "social/museo-egizio-1.jpg"
copy "photos/programma sociale/Museo_Egizio2.jpg"      "social/museo-egizio-2.jpg"
copy "photos/programma sociale/Torino_Notturna.jpg"    "social/torino-notturna.jpg"
copy "photos/programma sociale/Gran_Madre.jpg"         "social/gran-madre.jpg"
copy "photos/programma sociale/Villa_Regina.jpg"       "social/villa-regina.jpg"
copy "photos/programma sociale/Duomo_Milano.jpg"       "social/duomo-milano.jpg"
copy "photos/programma sociale/Museo_Torino.jpg"       "social/museo-torino.jpg"

echo "== pr =="
copy "photos/pr/palette.jpg"           "pr/palette.jpg"
copy "photos/pr/BW.png"                "pr/logo-bw.png"
copy "photos/pr/BW tot .jpg"           "pr/banner-bw.jpg"
copy "photos/pr/colored tot.jpg"       "pr/banner-colored.jpg"
copy "photos/pr/yellow left.jpg"       "pr/wing-warm-left.jpg"
copy "photos/pr/blue right.jpg"        "pr/wing-blue-right.jpg"

echo "== sponsors =="
copy "photos/sponsor/IAPS.jpg"             "sponsors/iaps.jpg"
copy "photos/sponsor/IUPAP.png"            "sponsors/iupap.png"
copy "photos/sponsor/EPS.png"              "sponsors/eps.png"
copy "photos/sponsor/UNITO.png"            "sponsors/unito.png"
copy "photos/sponsor/UNIMI.png"            "sponsors/unimi.png"
copy "photos/sponsor/UNI_BICOCCA.png"      "sponsors/unimib.png"
copy "photos/sponsor/INFN.jpg"             "sponsors/infn.jpg"
copy "photos/sponsor/inrim.jpg"            "sponsors/inrim.jpg"
copy "photos/sponsor/POLIMI.png"           "sponsors/polimi.png"
copy "photos/sponsor/POLITO.png"           "sponsors/polito.png"
copy "photos/sponsor/Intesa_Sanpaolo.png"  "sponsors/intesa-sanpaolo.png"

echo "done."
